language: node_js
node_js:
- "16.17.0"

branches:
  only:
    - master

before_install:
 - npm -v

install:
  - npm install --legacy-peer-deps
  - npm install -g @angular/cli

script:
  - npm run build

deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: $BUCKET
  skip_cleanup: true
  local_dir: ./dist/tvshowapp
  on:
    branch: master
